In [184]:
import pandas as pd
import numpy as np

In [185]:
df = pd.read_csv('../Data/2025_full_data.csv')

C:\Users\abdelrahman\AppData\Local\Temp\ipykernel_27884\437088706.py:1: DtypeWarning: Columns (0: to_mfr, 1: caseid_rpsr, 2: rpsr_cod_rpsr) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../Data/2025_full_data.csv')

In [186]:
df.head()

,primaryid,caseid,caseversion,i_f_code,event_dt,mfr_dt,init_fda_dt,fda_dt,rept_cod,auth_num,...,end_dt_ther,dur_ther,dur_cod_ther,caseid_outc,outc_cod_outc,caseid_rpsr,rpsr_cod_rpsr,caseid_indi,indi_drug_seq_indi,indi_pt_indi
0,100294532,10029453,2,F,NaN,20250319,20140322,20250326,EXP,NaN,...,"nan, nan","nan, nan","nan, nan",10029453,OT,NaN,NaN,"10029453, 10029453, 10029453, 10029453, 100294...","1, 2, 3, 4, 5, 7","Breast cancer metastatic, Breast cancer metast..."
1,100496573,10049657,3,F,20111201.0,20140324,20140401,20250307,EXP,NaN,...,"nan, 201202.0, nan, nan","nan, 14892.0, nan, nan","nan, HR, nan, nan",10049657,OT,NaN,NaN,"10049657, 10049657, 10049657","1, 5, 6","Glycogen storage disease type II, Premedicatio..."
2,100546853,10054685,3,F,20130901.0,20140414,20140402,20250227,PER,NaN,...,"20121015.0, 20121015.0, 20121015.0, 20121015.0...","nan, nan, 1.0, nan, nan, nan, nan, nan, nan, nan","nan, nan, DAY, nan, nan, nan, nan, nan, nan, nan",NaN,NaN,NaN,NaN,10054685,1,Maternal exposure during breast feeding
3,1005762122,10057621,22,F,20140204.0,20250106,20140404,20250110,EXP,NaN,...,"nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...",10057621,HO,NaN,NaN,"10057621, 10057621, 10057621, 10057621, 100576...","1, 39, 40, 41, 42, 43, 44, 45, 46, 47","Asthma, Product used for unknown indication, P..."
4,100683138,10068313,8,F,20140101.0,20250129,20140409,20250203,PER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10068313, 10068313, 10068313","1, 3, 5","Menopausal symptoms, Fibromyalgia, Drug hypers..."

In [187]:
df.columns

Index(['primaryid', 'caseid', 'caseversion', 'i_f_code', 'event_dt', 'mfr_dt',
       'init_fda_dt', 'fda_dt', 'rept_cod', 'auth_num', 'mfr_num', 'mfr_sndr',
       'lit_ref', 'age', 'age_cod', 'age_grp', 'sex', 'e_sub', 'wt', 'wt_cod',
       'rept_dt', 'to_mfr', 'occp_cod', 'reporter_country', 'occr_country',
       'caseid_drug', 'drug_seq_drug', 'role_cod_drug', 'drugname_drug',
       'prod_ai_drug', 'val_vbm_drug', 'route_drug', 'dose_vbm_drug',
       'cum_dose_chr_drug', 'cum_dose_unit_drug', 'dechal_drug', 'rechal_drug',
       'lot_num_drug', 'exp_dt_drug', 'nda_num_drug', 'dose_amt_drug',
       'dose_unit_drug', 'dose_form_drug', 'dose_freq_drug', 'caseid_reac',
       'pt_reac', 'drug_rec_act_reac', 'caseid_ther', 'dsg_drug_seq_ther',
       'start_dt_ther', 'end_dt_ther', 'dur_ther', 'dur_cod_ther',
       'caseid_outc', 'outc_cod_outc', 'caseid_rpsr', 'rpsr_cod_rpsr',
       'caseid_indi', 'indi_drug_seq_indi', 'indi_pt_indi'],
      dtype='str')

In [188]:
df.isna().sum()/len(df) * 100

primaryid              0.000000
caseid                 0.000000
caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
mfr_dt                 0.000000
init_fda_dt            0.000000
fda_dt                 0.000000
rept_cod               0.000000
auth_num              90.759371
mfr_num                3.367350
mfr_sndr               0.000000
lit_ref               90.856252
age                   39.685763
age_cod               39.681807
age_grp               63.983483
sex                   19.778366
e_sub                  0.000000
wt                    83.082382
wt_cod                83.082444
rept_dt                0.000000
to_mfr                96.810832
occp_cod              13.877018
reporter_country       0.000124
occr_country           4.925116
caseid_drug            0.000000
drug_seq_drug          0.000000
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug            11.688442
dose_vbm_drug         12.029412
cum_dose_chr_drug     46.073434
cum_dose_unit_drug    46.073434
dechal_drug           14.628018
rechal_drug           35.208761
lot_num_drug          26.961923
exp_dt_drug           46.394311
nda_num_drug           4.593544
dose_amt_drug         24.663667
dose_unit_drug        24.663667
dose_form_drug        14.453978
dose_freq_drug        31.765984
caseid_reac            0.000000
pt_reac                0.000000
drug_rec_act_reac     37.487233
caseid_ther           51.015800
dsg_drug_seq_ther     51.015800
start_dt_ther         53.154050
end_dt_ther           72.696242
dur_ther              75.461716
dur_cod_ther          75.462025
caseid_outc           43.137753
outc_cod_outc         43.137753
caseid_rpsr           97.316940
rpsr_cod_rpsr         97.316940
caseid_indi            6.974894
indi_drug_seq_indi     6.974894
indi_pt_indi           6.974894
dtype: float64

In [189]:
cols_to_drop = [
    'mfr_dt', 'init_fda_dt', 'fda_dt', 
    'auth_num',
    'lit_ref',
    'age_grp',
    'rpsr_cod_rpsr',
    'primaryid',
    'caseid', 'caseid_drug', 'caseid_reac', 'caseid_ther', 'caseid_outc', 'caseid_rpsr', 'caseid_indi',
    'mfr_num',
    'to_mfr',
    'reporter_country',
    'drug_seq_drug','dsg_drug_seq_ther','indi_drug_seq_indi',
    'lot_num_drug',
    'start_dt_ther',
    'end_dt_ther',
    'dur_ther','dur_cod_ther'

]

df = df.drop(columns=cols_to_drop)

In [190]:
df.head()

,caseversion,i_f_code,event_dt,rept_cod,mfr_sndr,age,age_cod,sex,e_sub,wt,...,exp_dt_drug,nda_num_drug,dose_amt_drug,dose_unit_drug,dose_form_drug,dose_freq_drug,pt_reac,drug_rec_act_reac,outc_cod_outc,indi_pt_indi
0,2,F,NaN,EXP,NOVARTIS,53.0,YR,F,Y,NaN,...,"nan, nan, nan, nan, nan, nan, nan, nan","20726.0, nan, nan, nan, nan, nan, nan, nan","nan, nan, nan, nan, nan, nan, nan, nan","nan, nan, nan, nan, nan, nan, nan, nan","nan, nan, nan, nan, nan, nan, nan, nan","nan, nan, nan, nan, nan, nan, nan, nan","Asthenia, Breast cancer metastatic, Palmar-pla...","nan, nan, nan, nan, nan, nan",OT,"Breast cancer metastatic, Breast cancer metast..."
1,3,F,20111201.0,EXP,SANOFI AVENTIS,12.0,YR,M,Y,30.0,...,"nan, nan, nan, nan, nan, nan","125141.0, 125141.0, 125141.0, 125141.0, nan, nan","20.0, nan, 10.0, 20.0, nan, nan","MG/KG, nan, MG/KG, MG/KG, nan, nan","Powder for solution for infusion, Powder for s...","QOW, nan, QOW, QOW, nan, nan","Hepatic fibrosis, Red blood cell sedimentation...","nan, nan, nan, nan, nan, nan, nan, nan, nan, nan",OT,"Glycogen storage disease type II, Premedicatio..."
2,3,F,20130901.0,PER,AMGEN,1.0,YR,M,Y,NaN,...,"nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","103795.0, nan, nan, nan, nan, nan, nan, nan, n...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","Solution for injection, nan, nan, nan, nan, na...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","Increased tendency to bruise, Exposure via bre...","nan, nan",NaN,Maternal exposure during breast feeding
3,22,F,20140204.0,EXP,ROCHE,57.0,YR,M,Y,53.0,...,"nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","103976.0, 103976.0, 103976.0, 103976.0, 103976...","225.0, 225.0, 375.0, 300.0, 225.0, nan, 375.0,...","MG, MG, MG, MG, MG, nan, MG, MG, MG, MG, MG, M...","INJECTION, SOLUTION, INJECTION, SOLUTION, INJE...","nan, nan, nan, nan, nan, nan, Q3W, nan, nan, n...","Dizziness, Dysphonia, Rhinitis allergic, Photo...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...",HO,"Asthma, Product used for unknown indication, P..."
4,8,F,20140101.0,PER,PFIZER,69.0,YR,F,Y,72.0,...,"nan, nan, nan, nan, nan","20527.0, 20527.0, nan, nan, nan","nan, nan, 60.0, 60.0, nan","nan, nan, MG, MG, nan","Tablet, Tablet, nan, nan, nan","nan, nan, nan, QD, nan","Hot flush, Feeling abnormal, Abdominal pain up...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...",NaN,"Menopausal symptoms, Fibromyalgia, Drug hypers..."

In [191]:
df.columns

Index(['caseversion', 'i_f_code', 'event_dt', 'rept_cod', 'mfr_sndr', 'age',
       'age_cod', 'sex', 'e_sub', 'wt', 'wt_cod', 'rept_dt', 'occp_cod',
       'occr_country', 'role_cod_drug', 'drugname_drug', 'prod_ai_drug',
       'val_vbm_drug', 'route_drug', 'dose_vbm_drug', 'cum_dose_chr_drug',
       'cum_dose_unit_drug', 'dechal_drug', 'rechal_drug', 'exp_dt_drug',
       'nda_num_drug', 'dose_amt_drug', 'dose_unit_drug', 'dose_form_drug',
       'dose_freq_drug', 'pt_reac', 'drug_rec_act_reac', 'outc_cod_outc',
       'indi_pt_indi'],
      dtype='str')

In [192]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1617444 entries, 0 to 1617443
Data columns (total 34 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   caseversion         1617444 non-null  int64
 1   i_f_code            1617444 non-null  str
 2   event_dt            707328 non-null   float64
 3   rept_cod            1617444 non-null  str
 4   mfr_sndr            1617444 non-null  str
 5   age                 975549 non-null   float64
 6   age_cod             975613 non-null   str
 7   sex                 1297540 non-null  str
 8   e_sub               1617444 non-null  str
 9   wt                  273633 non-null   float64
 10  wt_cod              273632 non-null   str
 11  rept_dt             1617444 non-null  int64
 12  occp_cod            1392991 non-null  str
 13  occr_country        1537783 non-null  str
 14  role_cod_drug       1617444 non-null  str
 15  drugname_drug       1617444 non-null  str
 16  prod_ai_drug        1617444 non-null  str
 17  val_vbm_drug        1617444 non-null  str
 18  route_drug          1428390 non-null  str
 19  dose_vbm_drug       1422875 non-null  str
 20  cum_dose_chr_drug   872232 non-null   str
 21  cum_dose_unit_drug  872232 non-null   str
 22  dechal_drug         1380844 non-null  str
 23  rechal_drug         1047962 non-null  str
 24  exp_dt_drug         867042 non-null   str
 25  nda_num_drug        1543146 non-null  str
 26  dose_amt_drug       1218523 non-null  str
 27  dose_unit_drug      1218523 non-null  str
 28  dose_form_drug      1383659 non-null  str
 29  dose_freq_drug      1103647 non-null  str
 30  pt_reac             1617444 non-null  str
 31  drug_rec_act_reac   1011109 non-null  str
 32  outc_cod_outc       919715 non-null   str
 33  indi_pt_indi        1504629 non-null  str
dtypes: float64(3), int64(2), str(29)
memory usage: 419.6 MB

In [193]:
df.describe()

        caseversion      event_dt            age             wt       rept_dt
count  1.617444e+06  7.073280e+05  975549.000000  273633.000000  1.617444e+06
mean   1.822906e+00  2.024050e+07      53.941827      73.944933  2.025067e+07
std    2.575601e+00  3.440997e+04      34.785563     182.283928  7.092877e+03
min    1.000000e+00  1.015031e+07       0.000000       0.000000  2.000022e+07
25%    1.000000e+00  2.024050e+07      39.000000      58.000000  2.025040e+07
50%    1.000000e+00  2.025010e+07      58.000000      71.000000  2.025070e+07
75%    2.000000e+00  2.025052e+07      71.000000      87.075000  2.025093e+07
max    1.510000e+02  2.444110e+07   24743.000000   89145.000000  2.925061e+07

In [194]:
def convert_to_kg(row):
    if row['wt_cod'] == 'LBS':
        return row['wt'] * 0.453592
    else:  # kg
        return row['wt']

df['wt'] = df.apply(convert_to_kg, axis=1)

In [195]:
df.columns

Index(['caseversion', 'i_f_code', 'event_dt', 'rept_cod', 'mfr_sndr', 'age',
       'age_cod', 'sex', 'e_sub', 'wt', 'wt_cod', 'rept_dt', 'occp_cod',
       'occr_country', 'role_cod_drug', 'drugname_drug', 'prod_ai_drug',
       'val_vbm_drug', 'route_drug', 'dose_vbm_drug', 'cum_dose_chr_drug',
       'cum_dose_unit_drug', 'dechal_drug', 'rechal_drug', 'exp_dt_drug',
       'nda_num_drug', 'dose_amt_drug', 'dose_unit_drug', 'dose_form_drug',
       'dose_freq_drug', 'pt_reac', 'drug_rec_act_reac', 'outc_cod_outc',
       'indi_pt_indi'],
      dtype='str')

In [196]:
df['wt']

0           NaN
1          30.0
2           NaN
3          53.0
4          72.0
           ...
1617439     NaN
1617440    44.0
1617441     NaN
1617442     NaN
1617443     NaN
Name: wt, Length: 1617444, dtype: float64

In [197]:
df['wt_cod'].value_counts()

wt_cod
KG     272932
LBS       700
Name: count, dtype: int64

In [198]:
df = df.drop(columns=['wt_cod'])

In [199]:
df.isna().sum()/len(df) * 100

caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
rept_cod               0.000000
mfr_sndr               0.000000
age                   39.685763
age_cod               39.681807
sex                   19.778366
e_sub                  0.000000
wt                    83.082382
rept_dt                0.000000
occp_cod              13.877018
occr_country           4.925116
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug            11.688442
dose_vbm_drug         12.029412
cum_dose_chr_drug     46.073434
cum_dose_unit_drug    46.073434
dechal_drug           14.628018
rechal_drug           35.208761
exp_dt_drug           46.394311
nda_num_drug           4.593544
dose_amt_drug         24.663667
dose_unit_drug        24.663667
dose_form_drug        14.453978
dose_freq_drug        31.765984
pt_reac                0.000000
drug_rec_act_reac     37.487233
outc_cod_outc         43.137753
indi_pt_indi           6.974894
dtype: float64

In [200]:
df["age"].median()

df["age"].mean()

np.float64(53.94182660225165)

In [201]:
df['age_cod'].value_counts()

age_cod
YR     954421
DEC     15030
MON      4493
DY       1105
WK        514
HR         50
Name: count, dtype: int64

In [202]:
def convert_to_years(row):
    code = row['age_cod'].strip().lower()

    if code == 'yr':
        return row['age']
    elif code == 'dec':
        return row['age'] * 10
    elif code == 'mon':
        return row['age'] / 12
    elif code == 'wk':
        return row['age'] / 52
    elif code == 'dy':
        return row['age'] / 365
    elif code == 'hr':
        return row['age'] / (365 * 24)
    else:
        return None
df['age_cod'] = df['age_cod'].fillna('').astype(str)
df['age'] = df.apply(convert_to_years, axis=1)

In [203]:
df.drop(columns=['age_cod'], inplace=True)

In [204]:
df.columns

Index(['caseversion', 'i_f_code', 'event_dt', 'rept_cod', 'mfr_sndr', 'age',
       'sex', 'e_sub', 'wt', 'rept_dt', 'occp_cod', 'occr_country',
       'role_cod_drug', 'drugname_drug', 'prod_ai_drug', 'val_vbm_drug',
       'route_drug', 'dose_vbm_drug', 'cum_dose_chr_drug',
       'cum_dose_unit_drug', 'dechal_drug', 'rechal_drug', 'exp_dt_drug',
       'nda_num_drug', 'dose_amt_drug', 'dose_unit_drug', 'dose_form_drug',
       'dose_freq_drug', 'pt_reac', 'drug_rec_act_reac', 'outc_cod_outc',
       'indi_pt_indi'],
      dtype='str')

In [205]:
df.isna().sum()/len(df) * 100

caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
rept_cod               0.000000
mfr_sndr               0.000000
age                   39.685825
sex                   19.778366
e_sub                  0.000000
wt                    83.082382
rept_dt                0.000000
occp_cod              13.877018
occr_country           4.925116
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug            11.688442
dose_vbm_drug         12.029412
cum_dose_chr_drug     46.073434
cum_dose_unit_drug    46.073434
dechal_drug           14.628018
rechal_drug           35.208761
exp_dt_drug           46.394311
nda_num_drug           4.593544
dose_amt_drug         24.663667
dose_unit_drug        24.663667
dose_form_drug        14.453978
dose_freq_drug        31.765984
pt_reac                0.000000
drug_rec_act_reac     37.487233
outc_cod_outc         43.137753
indi_pt_indi           6.974894
dtype: float64

In [206]:
print(df['age'].median())
print(df['age'].mean())

59.0
54.63585923492996

In [207]:
df['age']=df['age'].fillna(df['age'].mean())

In [208]:
df.isna().sum()/len(df) * 100

caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
rept_cod               0.000000
mfr_sndr               0.000000
age                    0.000000
sex                   19.778366
e_sub                  0.000000
wt                    83.082382
rept_dt                0.000000
occp_cod              13.877018
occr_country           4.925116
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug            11.688442
dose_vbm_drug         12.029412
cum_dose_chr_drug     46.073434
cum_dose_unit_drug    46.073434
dechal_drug           14.628018
rechal_drug           35.208761
exp_dt_drug           46.394311
nda_num_drug           4.593544
dose_amt_drug         24.663667
dose_unit_drug        24.663667
dose_form_drug        14.453978
dose_freq_drug        31.765984
pt_reac                0.000000
drug_rec_act_reac     37.487233
outc_cod_outc         43.137753
indi_pt_indi           6.974894
dtype: float64

In [209]:
df['sex'].value_counts()

sex
F      776053
M      520451
UNK      1036
Name: count, dtype: int64

In [210]:
df['sex'] = df['sex'].replace('UNK', None)

In [211]:
df.isna().sum()/len(df) * 100

caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
rept_cod               0.000000
mfr_sndr               0.000000
age                    0.000000
sex                   19.842418
e_sub                  0.000000
wt                    83.082382
rept_dt                0.000000
occp_cod              13.877018
occr_country           4.925116
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug            11.688442
dose_vbm_drug         12.029412
cum_dose_chr_drug     46.073434
cum_dose_unit_drug    46.073434
dechal_drug           14.628018
rechal_drug           35.208761
exp_dt_drug           46.394311
nda_num_drug           4.593544
dose_amt_drug         24.663667
dose_unit_drug        24.663667
dose_form_drug        14.453978
dose_freq_drug        31.765984
pt_reac                0.000000
drug_rec_act_reac     37.487233
outc_cod_outc         43.137753
indi_pt_indi           6.974894
dtype: float64

In [212]:
df['sex']=df['sex'].fillna(df['sex'].mode()[0])

In [213]:
df['occp_cod'].value_counts()

occp_cod
CN    611933
HP    360323
MD    329762
PH     80662
LW     10311
Name: count, dtype: int64

In [214]:
df['occp_cod']=df['occp_cod'].fillna(df['occp_cod'].mode()[0])

In [215]:
df.isna().sum()/len(df) * 100

caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
rept_cod               0.000000
mfr_sndr               0.000000
age                    0.000000
sex                    0.000000
e_sub                  0.000000
wt                    83.082382
rept_dt                0.000000
occp_cod               0.000000
occr_country           4.925116
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug            11.688442
dose_vbm_drug         12.029412
cum_dose_chr_drug     46.073434
cum_dose_unit_drug    46.073434
dechal_drug           14.628018
rechal_drug           35.208761
exp_dt_drug           46.394311
nda_num_drug           4.593544
dose_amt_drug         24.663667
dose_unit_drug        24.663667
dose_form_drug        14.453978
dose_freq_drug        31.765984
pt_reac                0.000000
drug_rec_act_reac     37.487233
outc_cod_outc         43.137753
indi_pt_indi           6.974894
dtype: float64

In [216]:
df['occr_country'].value_counts()

occr_country
US    988902
CA    103819
EU     89419
JP     65794
GB     59818
       ...
XK         1
AW         1
TM         1
FJ         1
JE         1
Name: count, Length: 196, dtype: int64

In [217]:
df['occr_country']=df['occr_country'].fillna(df['occr_country'].mode()[0])

In [218]:
df['route_drug']

0          Unknown, Unknown, Unknown, Unknown, Unknown, U...
1          Intravenous (not otherwise specified), Intrave...
2          Transmammary, nan, nan, nan, nan, nan, nan, na...
3          Subcutaneous, Subcutaneous, Subcutaneous, Subc...
4                                  Oral, Oral, nan, nan, nan
                                 ...
1617439    Intramuscular, Intramuscular, nan, Unknown, Un...
1617440    Intravenous (not otherwise specified), Intrave...
1617441    Transplacental, Transplacental, Transplacental...
1617442    Unknown, Unknown, nan, Unknown, nan, Unknown, ...
1617443                   Unknown, Unknown, Unknown, Unknown
Name: route_drug, Length: 1617444, dtype: str

In [219]:
# # 1) Remove noise words and extra commas/spaces
s = (
    df["route_drug"]
    .astype("string")
    .str.replace(r"(?i)\b(unknown|nan|none)\b", "", regex=True)
    .str.replace(r"\s*,\s*", ", ", regex=True)
    .str.replace(r"^,\s*|\s*,$", "", regex=True)
    .str.replace(r"(,\s*){2,}", ", ", regex=True)
    .str.strip()
    .replace("", pd.NA)
)

# 2) Fill missing with the most common route
fill_value = s.mode().iat[0] if not s.mode().empty else "Unknown"
df["route_drug"] = s.fillna(fill_value)

# 3) Quick check
df["route_drug"].value_counts().head(20)

route_drug
,                                                                               673113
Subcutaneous                                                                    172945
Oral                                                                            125543
Subcutaneous,                                                                    64521
Oral,                                                                            59044
Subcutaneous, Subcutaneous                                                       40015
Oral, Oral                                                                       30409
Oral, Oral,                                                                      21295
Intravenous (not otherwise specified)                                            21049
Subcutaneous, Subcutaneous,                                                      14501
Intravenous (not otherwise specified),                                           11787
Oral, Oral, Oral                                                                  9430
Subcutaneous, Subcutaneous, Subcutaneous, Subcutaneous                            8923
Intravenous (not otherwise specified), Intravenous (not otherwise specified)      8346
Intravenous drip                                                                  8019
Subcutaneous, Subcutaneous, Subcutaneous                                          7280
Intra-uterine                                                                     7172
Ophthalmic                                                                        6991
Other                                                                             6700
Topical                                                                           6517
Name: count, dtype: Int64

In [220]:
df['route_drug']

0                                                          ,
1          Intravenous (not otherwise specified), Intrave...
2                                   Transmammary, Oral, Oral
3          Subcutaneous, Subcutaneous, Subcutaneous, Subc...
4                                                Oral, Oral,
                                 ...
1617439                        Intramuscular, Intramuscular,
1617440    Intravenous (not otherwise specified), Intrave...
1617441    Transplacental, Transplacental, Transplacental...
1617442                                                    ,
1617443                                                    ,
Name: route_drug, Length: 1617444, dtype: string

In [221]:
df['dose_vbm_drug']

0                     UNK, UNK, UNK, UNK, UNK, UNK, UNK, UNK
1          20 mg/kg,QOW, UNK UNK,UNK, 10 mg/kg,QOW, 20 mg...
2          UNK, UNK, UNK, UNK, UNK, UNK, UNK, UNK, UNK, U...
3          nan, nan, nan, nan, nan, nan, nan, nan, nan, n...
4          (estrogens conjugated 0.3mg , medroxyprogester...
                                 ...
1617439       30 mg, QMO, 30 mg, QMO, nan, 2 DF (325mg), UNK
1617440    nan, nan, nan, nan, nan, nan, nan, nan, nan, 0...
1617441    Unk (Maternal exposure during pregnancy), Unk ...
1617442    UNK, 24 mg/m2, QD (day 1-4), nan, UNK, nan, UN...
1617443                                   UNK, UNK, UNK, UNK
Name: dose_vbm_drug, Length: 1617444, dtype: str

In [222]:
# 1) Remove noise words
s_dose = df["dose_vbm_drug"].astype("string")
s_dose = s_dose.str.replace(r"(?i)\b(unknown|nan|none|unk|na)\b", "", regex=True)

# 2) Aggressively clean up stray commas and spaces
s_dose = (
    s_dose
    .str.replace(r"[\s,]+", " ", regex=True) # Temporarily turn all comma/space blocks into single spaces
    # Alternatively, if you WANT to keep legitimate commas between multiple doses:
    # .str.replace(r"\s*,\s*", ",", regex=True)
    # .str.replace(r",+", ",", regex=True)
    # .str.replace(r"^[\s,]+|[\s,]+$", "", regex=True)
)

# For better separation, let's keep commas but clean them properly:
s_dose = df["dose_vbm_drug"].astype("string")
s_dose = s_dose.str.replace(r"(?i)\b(unknown|nan|none|unk|na)\b", "", regex=True)
s_dose = s_dose.str.replace(r"(\s*,\s*)+", ", ", regex=True) # Merge multiple commas into one ", " 
s_dose = s_dose.str.replace(r"^[\s,]+|[\s,]+$", "", regex=True) # Strip leading and trailing commas/spaces
s_dose = s_dose.replace("", pd.NA)


# 3) Fill missing with the most common dose
df["dose_vbm_drug"] = s_dose.fillna(s_dose.mode().iat[0] if not s_dose.mode().empty else "Unknown")

# 4) Quick check
df["dose_vbm_drug"].value_counts()

dose_vbm_drug
300 mg, QOW                                                                                                                                                                                                                                                                                                                                      639648
600 mg, 1X, 300 mg, QOW                                                                                                                                                                                                                                                                                                                           17292
200 mg, QOW                                                                                                                                                                                                                                                                                                                                        9347
34 milligram, qd                                                                                                                                                                                                                                                                                                                                   7901
Frequency : Daily;?                                                                                                                                                                                                                                                                                                                                6784
                                                                                                                                                                                                                                                                                                                                                  ...
600 mg, qw, 900 mg, q2w, 3 mg, qd, 5 mg, qd, 15 mg, qd, 100 mg, qd, 1500 ?g, qd                                                                                                                                                                                                                                                                       1
600 mg, 2250 mg, discontinued at week 12, 2250 mg, discontinued at week 12, 135 ug, 45 ug, 135 ug, 714 mg, 400 mg, 600 mg, 5 mg, 1 mg, 135 ug, 1.5 ug/kg, 1.5 microg/kg/week, 45 ug, 135 ug, 0.5 mg, 5 mg, 1 mg, 0.2 mg, 300 Milligram Daily;, 300 mg, 300 Milligram Daily;, 300 Milligram Daily;, 600 mg, QD, 800 mg, 300 mg, 800 mg, 100 mg         1
30 mg, QMO, 30 mg, QMO, 2 DF (325mg)                                                                                                                                                                                                                                                                                                                  1
(Maternal exposure during pregnancy), (Maternal exposure during pregnancy : ciclosporin in the first trimester was 320 mg/day and was, (Maternal exposure during pregnancy: 10 mg), (Maternal exposure during pregnancy : 125 mg)                                                                                                                     1
24 mg/m2, QD (day 1-4), 375 mg/m2, QD (weekly), 600 mg/m2, QD, 600 mg/m2, QD, (2x100 U/kg/d, 2x50U/kg/d resp)                                                                                                                                                                                                                                         1
Name: count, Length: 448342, dtype: Int64

In [223]:
df["dose_vbm_drug"].head(20)

0                                           300 mg, QOW
1           20 mg/kg, QOW, 10 mg/kg, QOW, 20 mg/kg, QOW
2                                    5 ml, qd, 1 ml, qd
3                                                   BID
4     (estrogens conjugated 0.3mg, medroxyprogestero...
5     2000 milligram/day in 2 administration, 250 mi...
6                                           300 mg, QOW
7                                           300 mg, QOW
8     Drug Dose First Administered is 528 Mg milligr...
9                                           300 mg, QOW
10    30 mg, Q4W (every 4 weeks), 30 mg, Q4W(every 4...
11                                          300 mg, QOW
12                                          300 mg, QOW
13                                          300 mg, QOW
14                                    400 milligram, qd
15    5 mg, 2x/day, 5 mg, 2x/day, 10 mg, 1x/day, 5 m...
16                                          300 mg, QOW
17    400 mg at weeks 0, 2, and 4 (infusion), 200 mg...
18    200 mg, BID, 400 mg, BID, 400 mg, QD, 200 mg, ...
19    received 3 times, 450 mg, BIW, Powder and solv...
Name: dose_vbm_drug, dtype: string

In [224]:
df.isna().sum()/len(df) * 100

caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
rept_cod               0.000000
mfr_sndr               0.000000
age                    0.000000
sex                    0.000000
e_sub                  0.000000
wt                    83.082382
rept_dt                0.000000
occp_cod               0.000000
occr_country           0.000000
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug             0.000000
dose_vbm_drug          0.000000
cum_dose_chr_drug     46.073434
cum_dose_unit_drug    46.073434
dechal_drug           14.628018
rechal_drug           35.208761
exp_dt_drug           46.394311
nda_num_drug           4.593544
dose_amt_drug         24.663667
dose_unit_drug        24.663667
dose_form_drug        14.453978
dose_freq_drug        31.765984
pt_reac                0.000000
drug_rec_act_reac     37.487233
outc_cod_outc         43.137753
indi_pt_indi           6.974894
dtype: float64

In [225]:
# 1) Clean noise words from cum_dose_chr_drug
s_cum_dose = df["cum_dose_chr_drug"].astype("string")
s_cum_dose = s_cum_dose.str.replace(r"(?i)\b(unknown|nan|none|unk|na)\b", "", regex=True)

# 2) Clean up commas and spaces
s_cum_dose = s_cum_dose.str.replace(r"(\s*,\s*)+", ", ", regex=True) # Merge multiple commas
s_cum_dose = s_cum_dose.str.replace(r"^[\s,]+|[\s,]+$", "", regex=True) # Strip leading/trailing
s_cum_dose = s_cum_dose.replace("", pd.NA)

# 3) Check if we can safely convert it to numeric (if it's purely numbers)
# We will use pd.to_numeric with errors='coerce' to see if it produces mostly valid numbers
numeric_cum_dose = pd.to_numeric(s_cum_dose, errors='coerce')

# If more than 50% of the non-null data is numeric, we treat it as a numeric column 
if numeric_cum_dose.notna().sum() > (s_cum_dose.notna().sum() * 0.5):
    # It's mostly numeric! Fill missing with the median.
    median_val = numeric_cum_dose.median() if not pd.isna(numeric_cum_dose.median()) else 0
    df["cum_dose_chr_drug"] = numeric_cum_dose.fillna(median_val)
else:
    # It's mostly text/categorical. Fill missing with the mode.
    fill_val = s_cum_dose.mode().iat[0] if not s_cum_dose.mode().empty else "Unknown"
    df["cum_dose_chr_drug"] = s_cum_dose.fillna(fill_val)

# 4) Quick check
df["cum_dose_chr_drug"].value_counts().head(20)

cum_dose_chr_drug
200.0           1573137
300.0               441
400.0               342
100.0               304
600.0               273
10.0                270
20.0                269
40.0                228
60.0                215
300.0, 300.0        208
80.0                207
1500.0              202
360.0, 360.0        202
1000.0              199
1200.0              187
50.0                185
240.0               184
500.0               177
800.0               177
120.0               162
Name: count, dtype: Int64

In [226]:
# 1) Standardize and clean noise words from cum_dose_unit_drug
s_unit = df["cum_dose_unit_drug"].astype("string").str.upper() # Standardize to uppercase for units (e.g., MG, ML)
s_unit = s_unit.str.replace(r"(?i)\b(UNKNOWN|NAN|NONE|UNK|NA)\b", "", regex=True)

# 2) Clean up commas and spaces
s_unit = s_unit.str.replace(r"(\s*,\s*)+", ", ", regex=True) # Merge multiple commas
s_unit = s_unit.str.replace(r"^[\s,]+|[\s,]+$", "", regex=True) # Strip leading/trailing
s_unit = s_unit.replace("", pd.NA)

# 3) Fill missing with the most common unit
fill_val_unit = s_unit.mode().iat[0] if not s_unit.mode().empty else "Unknown"
df["cum_dose_unit_drug"] = s_unit.fillna(fill_val_unit)

# 4) Quick check
df["cum_dose_unit_drug"]

0          MG
1          MG
2          MG
3          MG
4          MG
           ..
1617439    MG
1617440    MG
1617441    MG
1617442    MG
1617443    MG
Name: cum_dose_unit_drug, Length: 1617444, dtype: string

In [227]:
df["cum_dose_unit_drug"].head(20)

0                                                    MG
1                                                    MG
2                                                    MG
3                                                    MG
4                                                    MG
5                                                    MG
6                                                    MG
7                                                    MG
8                                                    MG
9                                                    MG
10                                                   MG
11                                                   MG
12                                                   MG
13                                                   MG
14                                                   MG
15                                                   MG
16                                                   MG
17                                                   MG
18    MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG, MG...
19                                                   MG
Name: cum_dose_unit_drug, dtype: string

In [228]:
df["cum_dose_chr_drug"].head(20)

0                                                 200.0
1                                                 200.0
2                                                 200.0
3                                                 200.0
4                                                 200.0
5                                                 200.0
6                                                 200.0
7                                                 200.0
8                                                 200.0
9                                                 200.0
10                                                200.0
11                                                200.0
12                                                200.0
13                                                200.0
14                                                200.0
15                                                200.0
16                                                200.0
17                                                200.0
18    56000.0, 56000.0, 56000.0, 56000.0, 56000.0, 5...
19                                                200.0
Name: cum_dose_chr_drug, dtype: string

In [229]:
df.isna().sum()/len(df) * 100

caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
rept_cod               0.000000
mfr_sndr               0.000000
age                    0.000000
sex                    0.000000
e_sub                  0.000000
wt                    83.082382
rept_dt                0.000000
occp_cod               0.000000
occr_country           0.000000
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug             0.000000
dose_vbm_drug          0.000000
cum_dose_chr_drug      0.000000
cum_dose_unit_drug     0.000000
dechal_drug           14.628018
rechal_drug           35.208761
exp_dt_drug           46.394311
nda_num_drug           4.593544
dose_amt_drug         24.663667
dose_unit_drug        24.663667
dose_form_drug        14.453978
dose_freq_drug        31.765984
pt_reac                0.000000
drug_rec_act_reac     37.487233
outc_cod_outc         43.137753
indi_pt_indi           6.974894
dtype: float64

In [230]:
df['dechal_drug'].value_counts().head(20)

dechal_drug
U                               335173
D                               111329
U, U                             83349
nan, nan                         82324
Y                                53984
nan, nan, nan                    30170
U, U, U, U                       29742
D, D                             29590
U, U, U                          28502
Y, Y                             21691
nan, nan, nan, nan               20202
U, nan                           17155
N                                17041
U, U, U, U, U                    11250
nan, nan, nan, nan, nan          11036
D, D, D                          10175
nan, nan, nan, nan, nan, nan      9002
nan, U                            8998
U, nan, nan                       8138
U, U, U, U, U, U                  7920
Name: count, dtype: int64

In [231]:
def encode_dechal(val):
    if pd.isna(val):
        return -1
    
    # Convert to uppercase string to be safe
    val_str = str(val).upper()
    
    # If the patient/report had ANY drug that was dechallenged (Y), consider it 1
    if 'Y' in val_str:
        return 1
    # If no drug was affirmatively dechallenged, but at least one wasn't (N), consider it 0
    elif 'N' in val_str:
        return 0
    # Otherwise, it's Unknown (U), Does not apply (D), or missing
    else:
        return -1

# Apply the custom parser across the entire column
df['dechal_drug'] = df['dechal_drug'].apply(encode_dechal)

# Quick check
df['dechal_drug'].value_counts()

dechal_drug
-1    960094
 0    463060
 1    194290
Name: count, dtype: int64

In [232]:
df['rechal_drug'].value_counts()

rechal_drug
nan, nan                                                                                                                                                                                                                                                       217518
U                                                                                                                                                                                                                                                              168043
nan, nan, nan                                                                                                                                                                                                                                                   94863
nan, nan, nan, nan                                                                                                                                                                                                                                              76512
nan, nan, nan, nan, nan                                                                                                                                                                                                                                         42118
                                                                                                                                                                                                                                                                ...
nan, nan, U, U, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan                                                                                                                                                  1
U, nan, nan, nan, nan, nan, U, nan, nan, nan, U, nan, U, nan, nan, nan                                                                                                                                                                                              1
Y, Y, U, U, U, U, U, U, U, U                                                                                                                                                                                                                                        1
U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, U, nan, nan, nan, nan, nan, nan, nan, nan                                                                                       1
U, U, U, U, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, U, U, U, U, nan, nan, nan, U, U, U, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan         1
Name: count, Length: 8156, dtype: int64

In [233]:
def encode_rechal(val):
    if pd.isna(val):
        return -1
    
    # Convert to uppercase string to be safe
    val_str = str(val).upper()
    
    # If the patient/report had ANY drug that was rechallenged (Y), consider it 1
    if 'Y' in val_str:
        return 1
    # If no drug was affirmatively rechallenged, but at least one wasn't (N), consider it 0
    elif 'N' in val_str:
        return 0
    # Otherwise, it's Unknown (U), Does not apply (D), or missing
    else:
        return -1

# Apply the custom parser across the entire column
df['rechal_drug'] = df['rechal_drug'].apply(encode_rechal)

# Quick check
df['rechal_drug'].value_counts()

rechal_drug
-1    813969
 0    796230
 1      7245
Name: count, dtype: int64

In [234]:
df.isna().sum()/len(df) * 100

caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
rept_cod               0.000000
mfr_sndr               0.000000
age                    0.000000
sex                    0.000000
e_sub                  0.000000
wt                    83.082382
rept_dt                0.000000
occp_cod               0.000000
occr_country           0.000000
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug             0.000000
dose_vbm_drug          0.000000
cum_dose_chr_drug      0.000000
cum_dose_unit_drug     0.000000
dechal_drug            0.000000
rechal_drug            0.000000
exp_dt_drug           46.394311
nda_num_drug           4.593544
dose_amt_drug         24.663667
dose_unit_drug        24.663667
dose_form_drug        14.453978
dose_freq_drug        31.765984
pt_reac                0.000000
drug_rec_act_reac     37.487233
outc_cod_outc         43.137753
indi_pt_indi           6.974894
dtype: float64

In [235]:
# Drop the original 'exp_dt_drug' column from the DataFrame
df.drop(columns=['exp_dt_drug'], inplace=True)

# Verify it was dropped
'exp_dt_drug' in df.columns

False

In [236]:
# Drop the extra 'exp_year' and 'exp_month' columns we created
df.drop(columns=['exp_year', 'exp_month'], inplace=True, errors='ignore')

# Quick check of what columns remain
df.columns

Index(['caseversion', 'i_f_code', 'event_dt', 'rept_cod', 'mfr_sndr', 'age',
       'sex', 'e_sub', 'wt', 'rept_dt', 'occp_cod', 'occr_country',
       'role_cod_drug', 'drugname_drug', 'prod_ai_drug', 'val_vbm_drug',
       'route_drug', 'dose_vbm_drug', 'cum_dose_chr_drug',
       'cum_dose_unit_drug', 'dechal_drug', 'rechal_drug', 'nda_num_drug',
       'dose_amt_drug', 'dose_unit_drug', 'dose_form_drug', 'dose_freq_drug',
       'pt_reac', 'drug_rec_act_reac', 'outc_cod_outc', 'indi_pt_indi'],
      dtype='str')

In [237]:
# Drop the 'nda_num_drug' column as it's just an identifier and likely noise for modeling
df.drop(columns=['nda_num_drug'], inplace=True, errors='ignore')

# Verify it was dropped
'nda_num_drug' in df.columns

False

In [238]:
df.isna().sum()/len(df) * 100

caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
rept_cod               0.000000
mfr_sndr               0.000000
age                    0.000000
sex                    0.000000
e_sub                  0.000000
wt                    83.082382
rept_dt                0.000000
occp_cod               0.000000
occr_country           0.000000
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug             0.000000
dose_vbm_drug          0.000000
cum_dose_chr_drug      0.000000
cum_dose_unit_drug     0.000000
dechal_drug            0.000000
rechal_drug            0.000000
dose_amt_drug         24.663667
dose_unit_drug        24.663667
dose_form_drug        14.453978
dose_freq_drug        31.765984
pt_reac                0.000000
drug_rec_act_reac     37.487233
outc_cod_outc         43.137753
indi_pt_indi           6.974894
dtype: float64

In [239]:
# 1) Convert to string
s_amt = df['dose_amt_drug'].astype(str)

# 2) Remove noise words (like 'nan', 'unknown', 'none', etc.)
s_amt = s_amt.str.replace(r"(?i)\b(unknown|nan|none|unk|na)\b", "", regex=True)

# 3) Clean up stray commas and spaces
s_amt = s_amt.str.replace(r"(\s*,\s*)+", ", ", regex=True)
s_amt = s_amt.str.replace(r"^[\s,]+|[\s,]+$", "", regex=True)

# 4) Replace empty strings with actual missing values
s_amt = s_amt.replace("", pd.NA)

# 5) Determine how to handle the numeric conversion vs strings
# Many rows have comma-separated numbers like "600.0, 300.0". 
# For modeling, a common strategy is to extract the median or max of these lists, 
# or just take the first reported valid number if order matters.
def get_numeric_representation(val):
    if pd.isna(val):
        return np.nan
    try:
        # Split by comma, convert to float (ignoring any completely broken strings)
        nums = [float(x.strip()) for x in val.split(',') if x.strip()]
        # Return median dosage amount if list is valid, else nan
        return np.median(nums) if nums else np.nan
    except:
        return np.nan

# Create numeric series
numeric_amt = s_amt.apply(get_numeric_representation)

# 6) Fill the remaining missing numbers with the overall median
median_amt = numeric_amt.median()
df['dose_amt_drug'] = numeric_amt.fillna(median_amt)

# 7) Check the clean result
df['dose_amt_drug'].value_counts().head(20)

dose_amt_drug
80.0     659734
300.0    142616
10.0      41156
200.0     40822
100.0     33871
5.0       33174
20.0      29610
40.0      28357
50.0      22070
450.0     21967
30.0      20881
15.0      20276
150.0     19023
25.0      17838
400.0     16722
2.5       16376
1.0       15626
2.0       12882
125.0     11754
600.0     11006
Name: count, dtype: int64

In [240]:
# 1) Standardize and clean noise words from dose_unit_drug
s_unit_amt = df["dose_unit_drug"].astype("string").str.upper() # Standardize to uppercase
s_unit_amt = s_unit_amt.str.replace(r"(?i)\b(UNKNOWN|NAN|NONE|UNK|NA)\b", "", regex=True)

# 2) Clean up commas and spaces
s_unit_amt = s_unit_amt.str.replace(r"(\s*,\s*)+", ", ", regex=True) # Merge multiple commas
s_unit_amt = s_unit_amt.str.replace(r"^[\s,]+|[\s,]+$", "", regex=True) # Strip leading/trailing

# 3) Deduplicate repeating units (e.g., "MG, MG, MG" -> "MG") as multiple drugs often share the same unit
def deduplicate_units(val):
    if pd.isna(val) or val.strip() == "":
        return pd.NA
    parts = [p.strip() for p in val.split(',') if p.strip()]
    unique_parts = list(dict.fromkeys(parts))
    return ", ".join(unique_parts)

s_unit_amt = s_unit_amt.apply(deduplicate_units)

# 4) Fill missing with the most common unit
fill_val_unit_amt = s_unit_amt.mode().iat[0] if not s_unit_amt.mode().empty else "Unknown"
df["dose_unit_drug"] = s_unit_amt.fillna(fill_val_unit_amt)

# 5) Quick check
df["dose_unit_drug"].value_counts().head(20)

dose_unit_drug
MG             1420001
UG               27034
GM               20216
ML               18667
IU               17158
MG, GM           14458
MG, UG           11404
MG/KG            10020
GM, MG            5759
MG, ML            5586
GTT               4751
MG/M**2           4721
MG/KG, MG         4720
MG, IU            4531
MG, MG/KG         4050
UG/KG             3166
ML, MG            2982
MG, MG/M**2       2626
UG, MG            2560
MG/M**2, MG       2335
Name: count, dtype: int64

In [241]:
# 1) Standardize and clean noise words from dose_form_drug
s_form = df["dose_form_drug"].astype("string").str.upper() # Standardize to uppercase
s_form = s_form.str.replace(r"(?i)\b(UNKNOWN|NAN|NONE|UNK|NA)\b", "", regex=True)

# 2) Clean up commas and spaces
s_form = s_form.str.replace(r"(\s*,\s*)+", ", ", regex=True) # Merge multiple commas
s_form = s_form.str.replace(r"^[\s,]+|[\s,]+$", "", regex=True) # Strip leading/trailing

# 3) Deduplicate repeating forms (e.g., "TABLET, TABLET" -> "TABLET")
# We can reuse the deduplicate_units function defined earlier!
s_form = s_form.apply(deduplicate_units)

# 4) Fill missing with the most common form
fill_val_form = s_form.mode().iat[0] if not s_form.mode().empty else "Unknown"
df["dose_form_drug"] = s_form.fillna(fill_val_form)

# 5) Quick check
df["dose_form_drug"].value_counts().head(20)

dose_form_drug
SOLUTION FOR INJECTION                          774576
TABLET                                          127760
SOLUTION FOR INJECTION IN PRE-FILLED PEN         95138
CAPSULE                                          65164
INJECTION                                        63912
FILM-COATED TABLET                               33740
SOLUTION FOR INFUSION                            33673
SOLUTION FOR INJECTION IN PRE-FILLED SYRINGE     24530
POWDER FOR SOLUTION FOR INFUSION                 16177
CONCENTRATE FOR SOLUTION FOR INFUSION            11398
INFUSION                                         11043
ORAL SOLUTION                                     9584
FORMULATION                                       9003
PROLONGED-RELEASE TABLET                          8679
NASAL SPRAY                                       7834
POWDER FOR INJECTION                              6993
EYE DROPS, SOLUTION                               6792
SUSPENSION FOR INJECTION                          6427
SOLUTION FOR INJECTION, TABLET                    6240
GEL FOR INJECTION                                 5974
Name: count, dtype: int64

In [242]:
df.isna().sum()/len(df) * 100

caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
rept_cod               0.000000
mfr_sndr               0.000000
age                    0.000000
sex                    0.000000
e_sub                  0.000000
wt                    83.082382
rept_dt                0.000000
occp_cod               0.000000
occr_country           0.000000
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug             0.000000
dose_vbm_drug          0.000000
cum_dose_chr_drug      0.000000
cum_dose_unit_drug     0.000000
dechal_drug            0.000000
rechal_drug            0.000000
dose_amt_drug          0.000000
dose_unit_drug         0.000000
dose_form_drug         0.000000
dose_freq_drug        31.765984
pt_reac                0.000000
drug_rec_act_reac     37.487233
outc_cod_outc         43.137753
indi_pt_indi           6.974894
dtype: float64

In [243]:
# 1) Standardize and clean noise words from dose_freq_drug
s_freq = df["dose_freq_drug"].astype("string").str.upper() # Standardize to uppercase
s_freq = s_freq.str.replace(r"(?i)\b(UNKNOWN|NAN|NONE|UNK|NA)\b", "", regex=True)

# 2) Clean up commas and spaces
s_freq = s_freq.str.replace(r"(\s*,\s*)+", ", ", regex=True) # Merge multiple commas
s_freq = s_freq.str.replace(r"^[\s,]+|[\s,]+$", "", regex=True) # Strip leading/trailing

# 3) Deduplicate repeating frequencies (e.g., "BID, BID" -> "BID")
s_freq = s_freq.apply(deduplicate_units)

# 4) Fill missing with the most common frequency
fill_val_freq = s_freq.mode().iat[0] if not s_freq.mode().empty else "Unknown"
df["dose_freq_drug"] = s_freq.fillna(fill_val_freq)

# 5) Quick check
df["dose_freq_drug"].value_counts().head(20)

dose_freq_drug
QD          1210903
QOW          126373
/WK           52828
BID           37413
1X, QOW       24450
Q12H          19077
/MONTH        16737
Q3W           15051
999            8361
QD, BID        6577
QD, /WK        5480
BID, QD        5430
1X             5427
/WK, QD        4380
TID            4209
QOD            3774
QD, Q12H       2952
QOW, QD        2727
Q12H, QD       2435
Q8H            2367
Name: count, dtype: int64

In [244]:
df['drug_rec_act_reac'].value_counts()

drug_rec_act_reac
nan, nan                                                        362499
nan, nan, nan                                                   207832
nan, nan, nan, nan                                              125795
nan, nan, nan, nan, nan                                          80025
nan, nan, nan, nan, nan, nan                                     53261
                                                                 ...
Epilepsy, nan, Epilepsy, nan, nan, nan                               1
Peripheral swelling, Neuropathy peripheral                           1
Normochromic normocytic anaemia                                      1
Vision blurred, Toothache, nan, nan, Headache, nan, nan, nan         1
nan, nan, nan, nan, nan, Hypoglycaemia                               1
Name: count, Length: 2804, dtype: int64

In [245]:
# 1) Standardize and clean noise words from drug_rec_act_reac
s_reac = df['drug_rec_act_reac'].astype("string").str.title() # Standardize casing (e.g., Headache)
s_reac = s_reac.str.replace(r"(?i)\b(UNKNOWN|NAN|NONE|UNK|NA)\b", "", regex=True)

# 2) Clean up commas and spaces
s_reac = s_reac.str.replace(r"(\s*,\s*)+", ", ", regex=True) # Merge multiple commas
s_reac = s_reac.str.replace(r"^[\s,]+|[\s,]+$", "", regex=True) # Strip leading/trailing

# 3) Deduplicate repeating reactions for the same case (e.g., "Headache, Headache" -> "Headache")
s_reac = s_reac.apply(deduplicate_units)

# 4) Fill missing with a placeholder ("Unknown" or "No Reaction Reported")
s_reac = s_reac.replace("", pd.NA)
fill_val_reac = s_reac.mode().iat[0] if not s_reac.mode().empty else "Unknown"
df["drug_rec_act_reac"] = s_reac.fillna(fill_val_reac)

# 5) Quick check
df["drug_rec_act_reac"].value_counts().head(20)

drug_rec_act_reac
Injection Site Pain          1614132
Rash                              60
Diarrhoea                         54
Pyrexia                           36
Infusion Related Reaction         32
Neutropenia                       30
Cytokine Release Syndrome         28
Headache                          27
Myelosuppression                  26
Anaphylactic Reaction             25
Hepatic Cytolysis                 22
Pancreatitis Acute                20
Arthralgia                        19
Pruritus                          19
Drug-Induced Liver Injury         18
Erythema                          16
Hypertension                      16
Rash Maculo-Papular               15
Acute Kidney Injury               15
Platelet Count Decreased          15
Name: count, dtype: int64

In [246]:
df.isna().sum()/len(df) * 100

caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
rept_cod               0.000000
mfr_sndr               0.000000
age                    0.000000
sex                    0.000000
e_sub                  0.000000
wt                    83.082382
rept_dt                0.000000
occp_cod               0.000000
occr_country           0.000000
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug             0.000000
dose_vbm_drug          0.000000
cum_dose_chr_drug      0.000000
cum_dose_unit_drug     0.000000
dechal_drug            0.000000
rechal_drug            0.000000
dose_amt_drug          0.000000
dose_unit_drug         0.000000
dose_form_drug         0.000000
dose_freq_drug         0.000000
pt_reac                0.000000
drug_rec_act_reac      0.000000
outc_cod_outc         43.137753
indi_pt_indi           6.974894
dtype: float64

In [250]:
# 1) Standardize and clean noise words from outc_cod_outc
s_outc = df['outc_cod_outc'].astype("string").str.upper()
s_outc = s_outc.str.replace(r"(?i)\b(UNKNOWN|NAN|NONE|UNK|NA)\b", "", regex=True)

# 2) Clean up commas and spaces
s_outc = s_outc.str.replace(r"(\s*,\s*)+", ", ", regex=True)
s_outc = s_outc.str.replace(r"^[\s,]+|[\s,]+$", "", regex=True)

# 3) Deduplicate AND SORT the outcomes
# Order of outcomes doesn't matter, so "HO, OT" is identical to "OT, HO". 
# Sorting ensures we don't accidentally create separate categories for the exact same patient outcomes.
def deduplicate_and_sort(val):
    if pd.isna(val) or str(val).strip() == "":
        return pd.NA
    parts = [p.strip() for p in str(val).split(',') if p.strip()]
    unique_sorted = sorted(list(set(parts)))
    return ", ".join(unique_sorted)

s_outc = s_outc.apply(deduplicate_and_sort)

# 4) Handle missing values safely
# Because outcomes are typically the target variable, making assumptions by filling with the mode 
# might introduce bias. Pinning it definitively as "Unknown" is the safest classification.
s_outc = s_outc.replace("", pd.NA)
df["outc_cod_outc"] = s_outc.fillna("Unknown")

# 5) Quick check
df["outc_cod_outc"].value_counts().head(20)

outc_cod_outc
Unknown                   697729
OT                        454090
HO                        151114
HO, OT                    125396
DE                         47313
DE, OT                     43848
HO, LT, OT                 14630
DE, HO, OT                 11259
HO, LT                      9535
LT, OT                      8638
DE, HO                      7452
DS, OT                      6832
LT                          6720
DS                          5984
DE, HO, LT, OT              3025
DS, HO, OT                  2784
CA, DE, DS, HO, LT, OT      2276
DS, HO, LT, OT              1890
DE, LT, OT                  1664
DE, DS, HO, LT, OT          1619
Name: count, dtype: int64

In [254]:
# 1) Standardize and clean noise words from indi_pt_indi (Indications)
s_indi = df['indi_pt_indi'].astype("string").str.title() # Use title case for standard disease/medical names

# Some specific FAERS-centric noise in indication fields BEFORE standard regex:
s_indi = s_indi.str.replace(r"(?i)\bProduct Used For Unknown Indication\b", "", regex=True)
# Also remove occurrences where removing 'Unknown' left weird artifacts
s_indi = s_indi.str.replace(r"(?i)\bProduct Used For\s*Indication\b", "", regex=True) 

# Remove standard nan/none/unk/unknown
s_indi = s_indi.str.replace(r"(?i)\b(UNKNOWN|NAN|NONE|UNK|NA)\b", "", regex=True)

# 2) Clean up commas and spaces
s_indi = s_indi.str.replace(r"(\s*,\s*)+", ", ", regex=True) # Merge multiple commas
s_indi = s_indi.str.replace(r"^[\s,]+|[\s,]+$", "", regex=True) # Strip leading/trailing

# 3) Deduplicate AND SORT the indications per patient
# A patient taking drugs for "Asthma, Hypertension" is the same as "Hypertension, Asthma".
# We use the deduplicate_and_sort function we wrote for the outcomes:
s_indi = s_indi.apply(deduplicate_and_sort)

# 4) Handle specific missing values 
s_indi = s_indi.replace("", pd.NA)
fill_val_indi = s_indi.mode().iat[0] if not s_indi.mode().empty else "Unknown"
df["indi_pt_indi"] = s_indi.fillna(fill_val_indi)

# 5) Quick check
df["indi_pt_indi"].value_counts().head(20)

indi_pt_indi
Dermatitis Atopic                        483095
Rheumatoid Arthritis                      39064
Asthma                                    33942
Crohn'S Disease                           31565
Plasma Cell Myeloma                       31001
Psoriasis                                 26488
Prostate Cancer                           21753
Colitis Ulcerative                        21492
Type 2 Diabetes Mellitus                  20145
Multiple Sclerosis                        17453
Weight Control                            15709
Pulmonary Arterial Hypertension           13104
Psoriatic Arthropathy                     12014
Eczema                                    11543
Parkinson'S Disease                       11043
Diabetes Mellitus                          9563
Breast Cancer                              8344
Chronic Obstructive Pulmonary Disease      8064
Eosinophilic Oesophagitis                  7934
Neurodermatitis                            7485
Name: count, dtype: int64

In [255]:
df['event_dt']

0                 NaN
1          20111201.0
2          20130901.0
3          20140204.0
4          20140101.0
              ...
1617439    20140101.0
1617440    20131009.0
1617441           NaN
1617442           NaN
1617443           NaN
Name: event_dt, Length: 1617444, dtype: float64