In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../Data/2025_full_data.csv')

C:\Users\abdelrahman\AppData\Local\Temp\ipykernel_9044\437088706.py:1: DtypeWarning: Columns (0: to_mfr, 1: caseid_rpsr, 2: rpsr_cod_rpsr) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../Data/2025_full_data.csv')

In [3]:
df.head()

,primaryid,caseid,caseversion,i_f_code,event_dt,mfr_dt,init_fda_dt,fda_dt,rept_cod,auth_num,...,end_dt_ther,dur_ther,dur_cod_ther,caseid_outc,outc_cod_outc,caseid_rpsr,rpsr_cod_rpsr,caseid_indi,indi_drug_seq_indi,indi_pt_indi
0,100294532,10029453,2,F,NaN,20250319,20140322,20250326,EXP,NaN,...,"nan, nan","nan, nan","nan, nan",10029453,OT,NaN,NaN,"10029453, 10029453, 10029453, 10029453, 100294...","1, 2, 3, 4, 5, 7","Breast cancer metastatic, Breast cancer metast..."
1,100496573,10049657,3,F,20111201.0,20140324,20140401,20250307,EXP,NaN,...,"nan, 201202.0, nan, nan","nan, 14892.0, nan, nan","nan, HR, nan, nan",10049657,OT,NaN,NaN,"10049657, 10049657, 10049657","1, 5, 6","Glycogen storage disease type II, Premedicatio..."
2,100546853,10054685,3,F,20130901.0,20140414,20140402,20250227,PER,NaN,...,"20121015.0, 20121015.0, 20121015.0, 20121015.0...","nan, nan, 1.0, nan, nan, nan, nan, nan, nan, nan","nan, nan, DAY, nan, nan, nan, nan, nan, nan, nan",NaN,NaN,NaN,NaN,10054685,1,Maternal exposure during breast feeding
3,1005762122,10057621,22,F,20140204.0,20250106,20140404,20250110,EXP,NaN,...,"nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...",10057621,HO,NaN,NaN,"10057621, 10057621, 10057621, 10057621, 100576...","1, 39, 40, 41, 42, 43, 44, 45, 46, 47","Asthma, Product used for unknown indication, P..."
4,100683138,10068313,8,F,20140101.0,20250129,20140409,20250203,PER,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10068313, 10068313, 10068313","1, 3, 5","Menopausal symptoms, Fibromyalgia, Drug hypers..."

In [4]:
df.columns

Index(['primaryid', 'caseid', 'caseversion', 'i_f_code', 'event_dt', 'mfr_dt',
       'init_fda_dt', 'fda_dt', 'rept_cod', 'auth_num', 'mfr_num', 'mfr_sndr',
       'lit_ref', 'age', 'age_cod', 'age_grp', 'sex', 'e_sub', 'wt', 'wt_cod',
       'rept_dt', 'to_mfr', 'occp_cod', 'reporter_country', 'occr_country',
       'caseid_drug', 'drug_seq_drug', 'role_cod_drug', 'drugname_drug',
       'prod_ai_drug', 'val_vbm_drug', 'route_drug', 'dose_vbm_drug',
       'cum_dose_chr_drug', 'cum_dose_unit_drug', 'dechal_drug', 'rechal_drug',
       'lot_num_drug', 'exp_dt_drug', 'nda_num_drug', 'dose_amt_drug',
       'dose_unit_drug', 'dose_form_drug', 'dose_freq_drug', 'caseid_reac',
       'pt_reac', 'drug_rec_act_reac', 'caseid_ther', 'dsg_drug_seq_ther',
       'start_dt_ther', 'end_dt_ther', 'dur_ther', 'dur_cod_ther',
       'caseid_outc', 'outc_cod_outc', 'caseid_rpsr', 'rpsr_cod_rpsr',
       'caseid_indi', 'indi_drug_seq_indi', 'indi_pt_indi'],
      dtype='str')

In [5]:
df.isna().sum()/len(df) * 100

primaryid              0.000000
caseid                 0.000000
caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
mfr_dt                 0.000000
init_fda_dt            0.000000
fda_dt                 0.000000
rept_cod               0.000000
auth_num              90.759371
mfr_num                3.367350
mfr_sndr               0.000000
lit_ref               90.856252
age                   39.685763
age_cod               39.681807
age_grp               63.983483
sex                   19.778366
e_sub                  0.000000
wt                    83.082382
wt_cod                83.082444
rept_dt                0.000000
to_mfr                96.810832
occp_cod              13.877018
reporter_country       0.000124
occr_country           4.925116
caseid_drug            0.000000
drug_seq_drug          0.000000
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug            11.688442
dose_vbm_drug         12.029412
cum_dose_chr_drug     46.073434
cum_dose_unit_drug    46.073434
dechal_drug           14.628018
rechal_drug           35.208761
lot_num_drug          26.961923
exp_dt_drug           46.394311
nda_num_drug           4.593544
dose_amt_drug         24.663667
dose_unit_drug        24.663667
dose_form_drug        14.453978
dose_freq_drug        31.765984
caseid_reac            0.000000
pt_reac                0.000000
drug_rec_act_reac     37.487233
caseid_ther           51.015800
dsg_drug_seq_ther     51.015800
start_dt_ther         53.154050
end_dt_ther           72.696242
dur_ther              75.461716
dur_cod_ther          75.462025
caseid_outc           43.137753
outc_cod_outc         43.137753
caseid_rpsr           97.316940
rpsr_cod_rpsr         97.316940
caseid_indi            6.974894
indi_drug_seq_indi     6.974894
indi_pt_indi           6.974894
dtype: float64

In [6]:
cols_to_drop = [
    'mfr_dt', 'init_fda_dt', 'fda_dt', 
    'auth_num',
    'lit_ref',
    'age_grp',
    'rpsr_cod_rpsr',
    'primaryid',
    'caseid', 'caseid_drug', 'caseid_reac', 'caseid_ther', 'caseid_outc', 'caseid_rpsr', 'caseid_indi',
    'mfr_num',
    'to_mfr',
    'reporter_country',
    'drug_seq_drug','dsg_drug_seq_ther','indi_drug_seq_indi',
    'lot_num_drug',
    'start_dt_ther',
    'end_dt_ther',
    'dur_ther'
]

df = df.drop(columns=cols_to_drop)

In [7]:
df.head()

,caseversion,i_f_code,event_dt,rept_cod,mfr_sndr,age,age_cod,sex,e_sub,wt,...,nda_num_drug,dose_amt_drug,dose_unit_drug,dose_form_drug,dose_freq_drug,pt_reac,drug_rec_act_reac,dur_cod_ther,outc_cod_outc,indi_pt_indi
0,2,F,NaN,EXP,NOVARTIS,53.0,YR,F,Y,NaN,...,"20726.0, nan, nan, nan, nan, nan, nan, nan","nan, nan, nan, nan, nan, nan, nan, nan","nan, nan, nan, nan, nan, nan, nan, nan","nan, nan, nan, nan, nan, nan, nan, nan","nan, nan, nan, nan, nan, nan, nan, nan","Asthenia, Breast cancer metastatic, Palmar-pla...","nan, nan, nan, nan, nan, nan","nan, nan",OT,"Breast cancer metastatic, Breast cancer metast..."
1,3,F,20111201.0,EXP,SANOFI AVENTIS,12.0,YR,M,Y,30.0,...,"125141.0, 125141.0, 125141.0, 125141.0, nan, nan","20.0, nan, 10.0, 20.0, nan, nan","MG/KG, nan, MG/KG, MG/KG, nan, nan","Powder for solution for infusion, Powder for s...","QOW, nan, QOW, QOW, nan, nan","Hepatic fibrosis, Red blood cell sedimentation...","nan, nan, nan, nan, nan, nan, nan, nan, nan, nan","nan, HR, nan, nan",OT,"Glycogen storage disease type II, Premedicatio..."
2,3,F,20130901.0,PER,AMGEN,1.0,YR,M,Y,NaN,...,"103795.0, nan, nan, nan, nan, nan, nan, nan, n...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","Solution for injection, nan, nan, nan, nan, na...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","Increased tendency to bruise, Exposure via bre...","nan, nan","nan, nan, DAY, nan, nan, nan, nan, nan, nan, nan",NaN,Maternal exposure during breast feeding
3,22,F,20140204.0,EXP,ROCHE,57.0,YR,M,Y,53.0,...,"103976.0, 103976.0, 103976.0, 103976.0, 103976...","225.0, 225.0, 375.0, 300.0, 225.0, nan, 375.0,...","MG, MG, MG, MG, MG, nan, MG, MG, MG, MG, MG, M...","INJECTION, SOLUTION, INJECTION, SOLUTION, INJE...","nan, nan, nan, nan, nan, nan, Q3W, nan, nan, n...","Dizziness, Dysphonia, Rhinitis allergic, Photo...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...",HO,"Asthma, Product used for unknown indication, P..."
4,8,F,20140101.0,PER,PFIZER,69.0,YR,F,Y,72.0,...,"20527.0, 20527.0, nan, nan, nan","nan, nan, 60.0, 60.0, nan","nan, nan, MG, MG, nan","Tablet, Tablet, nan, nan, nan","nan, nan, nan, QD, nan","Hot flush, Feeling abnormal, Abdominal pain up...","nan, nan, nan, nan, nan, nan, nan, nan, nan, n...",NaN,NaN,"Menopausal symptoms, Fibromyalgia, Drug hypers..."

In [8]:
df.columns

Index(['caseversion', 'i_f_code', 'event_dt', 'rept_cod', 'mfr_sndr', 'age',
       'age_cod', 'sex', 'e_sub', 'wt', 'wt_cod', 'rept_dt', 'occp_cod',
       'occr_country', 'role_cod_drug', 'drugname_drug', 'prod_ai_drug',
       'val_vbm_drug', 'route_drug', 'dose_vbm_drug', 'cum_dose_chr_drug',
       'cum_dose_unit_drug', 'dechal_drug', 'rechal_drug', 'exp_dt_drug',
       'nda_num_drug', 'dose_amt_drug', 'dose_unit_drug', 'dose_form_drug',
       'dose_freq_drug', 'pt_reac', 'drug_rec_act_reac', 'dur_cod_ther',
       'outc_cod_outc', 'indi_pt_indi'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1617444 entries, 0 to 1617443
Data columns (total 35 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   caseversion         1617444 non-null  int64
 1   i_f_code            1617444 non-null  str
 2   event_dt            707328 non-null   float64
 3   rept_cod            1617444 non-null  str
 4   mfr_sndr            1617444 non-null  str
 5   age                 975549 non-null   float64
 6   age_cod             975613 non-null   str
 7   sex                 1297540 non-null  str
 8   e_sub               1617444 non-null  str
 9   wt                  273633 non-null   float64
 10  wt_cod              273632 non-null   str
 11  rept_dt             1617444 non-null  int64
 12  occp_cod            1392991 non-null  str
 13  occr_country        1537783 non-null  str
 14  role_cod_drug       1617444 non-null  str
 15  drugname_drug       1617444 non-null  str
 16  prod_ai_drug        1617444 non-null  str
 17  val_vbm_drug        1617444 non-null  str
 18  route_drug          1428390 non-null  str
 19  dose_vbm_drug       1422875 non-null  str
 20  cum_dose_chr_drug   872232 non-null   str
 21  cum_dose_unit_drug  872232 non-null   str
 22  dechal_drug         1380844 non-null  str
 23  rechal_drug         1047962 non-null  str
 24  exp_dt_drug         867042 non-null   str
 25  nda_num_drug        1543146 non-null  str
 26  dose_amt_drug       1218523 non-null  str
 27  dose_unit_drug      1218523 non-null  str
 28  dose_form_drug      1383659 non-null  str
 29  dose_freq_drug      1103647 non-null  str
 30  pt_reac             1617444 non-null  str
 31  drug_rec_act_reac   1011109 non-null  str
 32  dur_cod_ther        396888 non-null   str
 33  outc_cod_outc       919715 non-null   str
 34  indi_pt_indi        1504629 non-null  str
dtypes: float64(3), int64(2), str(30)
memory usage: 431.9 MB

In [10]:
df.describe()

        caseversion      event_dt            age             wt       rept_dt
count  1.617444e+06  7.073280e+05  975549.000000  273633.000000  1.617444e+06
mean   1.822906e+00  2.024050e+07      53.941827      73.944933  2.025067e+07
std    2.575601e+00  3.440997e+04      34.785563     182.283928  7.092877e+03
min    1.000000e+00  1.015031e+07       0.000000       0.000000  2.000022e+07
25%    1.000000e+00  2.024050e+07      39.000000      58.000000  2.025040e+07
50%    1.000000e+00  2.025010e+07      58.000000      71.000000  2.025070e+07
75%    2.000000e+00  2.025052e+07      71.000000      87.075000  2.025093e+07
max    1.510000e+02  2.444110e+07   24743.000000   89145.000000  2.925061e+07

In [18]:
def convert_to_kg(row):
    if row['wt_cod'] == 'LBS':
        return row['wt'] * 0.453592
    else:  # kg
        return row['wt']

df['wt'] = df.apply(convert_to_kg, axis=1)

In [19]:
df.columns

Index(['caseversion', 'i_f_code', 'event_dt', 'rept_cod', 'mfr_sndr', 'age',
       'age_cod', 'sex', 'e_sub', 'wt', 'wt_cod', 'rept_dt', 'occp_cod',
       'occr_country', 'role_cod_drug', 'drugname_drug', 'prod_ai_drug',
       'val_vbm_drug', 'route_drug', 'dose_vbm_drug', 'cum_dose_chr_drug',
       'cum_dose_unit_drug', 'dechal_drug', 'rechal_drug', 'exp_dt_drug',
       'nda_num_drug', 'dose_amt_drug', 'dose_unit_drug', 'dose_form_drug',
       'dose_freq_drug', 'pt_reac', 'drug_rec_act_reac', 'dur_cod_ther',
       'outc_cod_outc', 'indi_pt_indi'],
      dtype='str')

In [20]:
df['wt']

0           NaN
1          30.0
2           NaN
3          53.0
4          72.0
           ...
1617439     NaN
1617440    44.0
1617441     NaN
1617442     NaN
1617443     NaN
Name: wt, Length: 1617444, dtype: float64

In [21]:
df['wt_cod'].value_counts()

wt_cod
KG     272932
LBS       700
Name: count, dtype: int64

In [22]:
df = df.drop(columns=['wt_cod'])

In [23]:
df.isna().sum()/len(df) * 100

caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
rept_cod               0.000000
mfr_sndr               0.000000
age                   39.685763
age_cod               39.681807
sex                   19.778366
e_sub                  0.000000
wt                    83.082382
rept_dt                0.000000
occp_cod              13.877018
occr_country           4.925116
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug            11.688442
dose_vbm_drug         12.029412
cum_dose_chr_drug     46.073434
cum_dose_unit_drug    46.073434
dechal_drug           14.628018
rechal_drug           35.208761
exp_dt_drug           46.394311
nda_num_drug           4.593544
dose_amt_drug         24.663667
dose_unit_drug        24.663667
dose_form_drug        14.453978
dose_freq_drug        31.765984
pt_reac                0.000000
drug_rec_act_reac     37.487233
dur_cod_ther          75.462025
outc_cod_outc         43.137753
indi_pt_indi           6.974894
dtype: float64

In [25]:
df["age"].median()

df["age"].mean()

np.float64(53.94182660225165)

In [26]:
df['age_cod'].value_counts()

age_cod
YR     954421
DEC     15030
MON      4493
DY       1105
WK        514
HR         50
Name: count, dtype: int64

In [30]:
def convert_to_years(row):
    code = row['age_cod'].strip().lower()

    if code == 'yr':
        return row['age']
    elif code == 'dec':
        return row['age'] * 10
    elif code == 'mon':
        return row['age'] / 12
    elif code == 'wk':
        return row['age'] / 52
    elif code == 'dy':
        return row['age'] / 365
    elif code == 'hr':
        return row['age'] / (365 * 24)
    else:
        return None
df['age_cod'] = df['age_cod'].fillna('').astype(str)
df['age'] = df.apply(convert_to_years, axis=1)

In [31]:
df.drop(columns=['age_cod'], inplace=True)

In [32]:
df.columns

Index(['caseversion', 'i_f_code', 'event_dt', 'rept_cod', 'mfr_sndr', 'age',
       'sex', 'e_sub', 'wt', 'rept_dt', 'occp_cod', 'occr_country',
       'role_cod_drug', 'drugname_drug', 'prod_ai_drug', 'val_vbm_drug',
       'route_drug', 'dose_vbm_drug', 'cum_dose_chr_drug',
       'cum_dose_unit_drug', 'dechal_drug', 'rechal_drug', 'exp_dt_drug',
       'nda_num_drug', 'dose_amt_drug', 'dose_unit_drug', 'dose_form_drug',
       'dose_freq_drug', 'pt_reac', 'drug_rec_act_reac', 'dur_cod_ther',
       'outc_cod_outc', 'indi_pt_indi'],
      dtype='str')

In [33]:
df.isna().sum()/len(df) * 100

caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
rept_cod               0.000000
mfr_sndr               0.000000
age                   39.685825
sex                   19.778366
e_sub                  0.000000
wt                    83.082382
rept_dt                0.000000
occp_cod              13.877018
occr_country           4.925116
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug            11.688442
dose_vbm_drug         12.029412
cum_dose_chr_drug     46.073434
cum_dose_unit_drug    46.073434
dechal_drug           14.628018
rechal_drug           35.208761
exp_dt_drug           46.394311
nda_num_drug           4.593544
dose_amt_drug         24.663667
dose_unit_drug        24.663667
dose_form_drug        14.453978
dose_freq_drug        31.765984
pt_reac                0.000000
drug_rec_act_reac     37.487233
dur_cod_ther          75.462025
outc_cod_outc         43.137753
indi_pt_indi           6.974894
dtype: float64

In [35]:
print(df['age'].median())
print(df['age'].mean())

59.0
54.63585923492996

In [36]:
df['age']=df['age'].fillna(df['age'].mean())

In [37]:
df.isna().sum()/len(df) * 100

caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
rept_cod               0.000000
mfr_sndr               0.000000
age                    0.000000
sex                   19.778366
e_sub                  0.000000
wt                    83.082382
rept_dt                0.000000
occp_cod              13.877018
occr_country           4.925116
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug            11.688442
dose_vbm_drug         12.029412
cum_dose_chr_drug     46.073434
cum_dose_unit_drug    46.073434
dechal_drug           14.628018
rechal_drug           35.208761
exp_dt_drug           46.394311
nda_num_drug           4.593544
dose_amt_drug         24.663667
dose_unit_drug        24.663667
dose_form_drug        14.453978
dose_freq_drug        31.765984
pt_reac                0.000000
drug_rec_act_reac     37.487233
dur_cod_ther          75.462025
outc_cod_outc         43.137753
indi_pt_indi           6.974894
dtype: float64

In [38]:
df['sex'].value_counts()

sex
F      776053
M      520451
UNK      1036
Name: count, dtype: int64

In [39]:
df['sex'] = df['sex'].replace('UNK', None)

In [40]:
df.isna().sum()/len(df) * 100

caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
rept_cod               0.000000
mfr_sndr               0.000000
age                    0.000000
sex                   19.842418
e_sub                  0.000000
wt                    83.082382
rept_dt                0.000000
occp_cod              13.877018
occr_country           4.925116
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug            11.688442
dose_vbm_drug         12.029412
cum_dose_chr_drug     46.073434
cum_dose_unit_drug    46.073434
dechal_drug           14.628018
rechal_drug           35.208761
exp_dt_drug           46.394311
nda_num_drug           4.593544
dose_amt_drug         24.663667
dose_unit_drug        24.663667
dose_form_drug        14.453978
dose_freq_drug        31.765984
pt_reac                0.000000
drug_rec_act_reac     37.487233
dur_cod_ther          75.462025
outc_cod_outc         43.137753
indi_pt_indi           6.974894
dtype: float64

In [41]:
df['sex']=df['sex'].fillna(df['sex'].mode()[0])

In [45]:
df['occp_cod'].value_counts()

occp_cod
CN    611933
HP    360323
MD    329762
PH     80662
LW     10311
Name: count, dtype: int64

In [46]:
df['occp_cod']=df['occp_cod'].fillna(df['occp_cod'].mode()[0])

In [47]:
df.isna().sum()/len(df) * 100

caseversion            0.000000
i_f_code               0.000000
event_dt              56.268780
rept_cod               0.000000
mfr_sndr               0.000000
age                    0.000000
sex                    0.000000
e_sub                  0.000000
wt                    83.082382
rept_dt                0.000000
occp_cod               0.000000
occr_country           4.925116
role_cod_drug          0.000000
drugname_drug          0.000000
prod_ai_drug           0.000000
val_vbm_drug           0.000000
route_drug            11.688442
dose_vbm_drug         12.029412
cum_dose_chr_drug     46.073434
cum_dose_unit_drug    46.073434
dechal_drug           14.628018
rechal_drug           35.208761
exp_dt_drug           46.394311
nda_num_drug           4.593544
dose_amt_drug         24.663667
dose_unit_drug        24.663667
dose_form_drug        14.453978
dose_freq_drug        31.765984
pt_reac                0.000000
drug_rec_act_reac     37.487233
dur_cod_ther          75.462025
outc_cod_outc         43.137753
indi_pt_indi           6.974894
dtype: float64

In [48]:
df['occr_country'].value_counts()

occr_country
US    988902
CA    103819
EU     89419
JP     65794
GB     59818
       ...
XK         1
AW         1
TM         1
FJ         1
JE         1
Name: count, Length: 196, dtype: int64

In [49]:
df['occr_country']=df['occr_country'].fillna(df['occr_country'].mode()[0])

In [ ]:
df['route_drug'].value_counts()

route_drug
Unknown                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    181964
Subcutaneous                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               170577
Oral                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       122108
Unknown, Unknown                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            45932
nan, nan                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    45363
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...
Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Oral, nan, nan, nan, nan, Oral, nan, nan, Oral, nan, nan, nan, nan         1
Intramuscular, Intramuscular, Intramuscular, Intramuscular, Intramuscular, Intramuscular, Subcutaneous, nan, nan, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
Unknown, nan, Unknown, Unknown, Unknown, Unknown, Unknown, Oral, Unknown, Unknown, Oral, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown                                                                                                                                                                                                                                                                                                                                                                                                                                       1
Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Intravenous (not otherwise specified), Subcutaneous, Subcutaneous, Subcutaneous, Subcutaneous, Subcutaneous, Subcutaneous, Subcutaneous, Subcutaneous, Subcutaneous, Unknown, nan, nan, nan, Subcutaneous, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, Oral, nan, nan, nan                                                                                                                                                                                                                                        1
Unknown, Unknown, nan, Unknown, nan, Unknown, Unknown, nan, Unknown, nan, Unknown, Unknown, nan, Unknown, Unknown, Unknown, nan, Unknown                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
Name: count, Length: 102372, dtype: int64

In [ ]:
# # 1) Remove noise words and extra commas/spaces
# s = (
#     df["route_drug"]
#     .astype("string")
#     .str.replace(r"(?i)\b(unknown|nan|none)\b", "", regex=True)
#     .str.replace(r"\s*,\s*", ", ", regex=True)
#     .str.replace(r"^,\s*|\s*,$", "", regex=True)
#     .str.replace(r"(,\s*){2,}", ", ", regex=True)
#     .str.strip()
#     .replace("", pd.NA)
# )

# # 2) Fill missing with the most common route
# fill_value = s.mode().iat[0] if not s.mode().empty else "Unknown"
# df["route_drug"] = s.fillna(fill_value)

# # 3) Quick check
# df["route_drug"].value_counts().head(20)

In [51]:
df['dose_vbm_drug'].value_counts()

dose_vbm_drug
UNK                                                                                                                                                                                                                                                                                                                                                                                                                                        142626
300 mg, QOW                                                                                                                                                                                                                                                                                                                                                                                                                                 50475
nan, nan                                                                                                                                                                                                                                                                                                                                                                                                                                    49144
UNK, UNK                                                                                                                                                                                                                                                                                                                                                                                                                                    27760
nan, nan, nan                                                                                                                                                                                                                                                                                                                                                                                                                               20004
                                                                                                                                                                                                                                                                                                                                                                                                                                            ...
UNK, nan, UNK, UNK, 600 mg, UNK, UNK, 2250 mg, discontinued at week 12, UNK, UNK, 2250 mg, discontinued at week 12, 135 ug, UNK, 45 ug, 135 ug, 714 mg, 400 mg, 600 mg, 5 mg, 1 mg, 135 ug, 1.5 ug/kg, 1.5 microg/kg/week, 45 ug, 135 ug, 0.5 mg, 5 mg, 1 mg, UNK, UNK, 0.2 mg, UNK, UNK, 300 Milligram Daily;, 300 mg, UNK, 300 Milligram Daily;, 300 Milligram Daily;, UNK, UNK, UNK, UNK, 600 mg, QD, 800 mg, 300 mg, 800 mg, 100 mg         1
30 mg, QMO, 30 mg, QMO, nan, 2 DF (325mg), UNK                                                                                                                                                                                                                                                                                                                                                                                                  1
nan, nan, nan, nan, nan, nan, nan, nan, nan, 0.9 mL ActPen, 0.9 mL Pre-Filled, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan                                                                                                                                                                                                                                 1
Unk (Maternal exposure during pregnancy), Unk (Maternal exposure during pregnancy : ciclosporin in the first trimester was 320 mg/day and was, UNK (Maternal exposure during pregnancy: 10 mg), UNK (Maternal exposure during pregnancy : 125 mg)                                                                                                                                                                                               1
UNK, 24 mg/m2, QD (day 1-4), nan, UNK, nan, UNK, 375 mg/m2, QD (weekly), nan, UNK, nan, 600 mg/m2, QD, 600 mg/m2, QD, nan, UNK, UNK, UNK (2x100 U/kg/d, 2x50U/kg/d resp), nan, UNK                                                                                                                                                                                                                                                              1
Name: count, Length: 534414, dtype: int64